# Generated by Django 5.1.4 on 2025-03-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('phone_number', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('problem', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('report', models.CharField(max_length=250)),
                ('next_meet', models.DateField()),
            ],
        ),
    ]
